version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: ["mongod", "--bind_ip_all"]